os: windows

install:
  - choco install -y conan

matrix:
    include:        
        - language: cpp
          script:
            - RefreshEnv.cmd
            - conan -v
            - mkdir build
            - cd build
            - cmake ..
            - cmake --build . --config Release