os: windows

install:
  - choco install -y conan
  - cmd /c RefreshEnv.cmd

matrix:
    include:        
        - language: cpp
          script:
            - mkdir build
            - cd build
            - cmake ..
            - cmake --build . --config Release