os: windows

install:
  - choco install -y conan

matrix:
    include:        
        - language: cpp
          script:
            - RefreshEnv.cmd
            - "C:\Program Files\Conan\conan\conan.exe" -v
            - mkdir build
            - cd build
            - cmake ..
            - cmake --build . --config Release