os: windows

install:
  - choco install -y conan
  - set PATH=C:\Program Files\Conan\conan;%PATH%
  - RefreshEnv.cmd
  - conan -v

matrix:
    include:        
        - language: cpp
          script:
            - mkdir build
            - cd build
            - cmake ..
            - cmake --build . --config Release