os: windows

install:
  - choco install conan --params="'/AddToPath:1'"

matrix:
    include:        
        - language: cpp
          script:
            - cmd //c "RefreshEnv.cmd" 
            - cmd //c "conan.exe"
            - conan -v
            - mkdir build
            - cd build
            - cmake ..
            - cmake --build . --config Release