os: windows

install:
  - choco install conan --params="'/AddToPath:1'"

matrix:
    include:        
        - language: cpp
          script:
           # - alias conan='cmd //c "RefreshEnv.cmd & conan.exe"'
          #  - conan -v
            - mkdir build
            - cd build
            - cmd //c "RefreshEnv.cmd & cmake .."
            - cmake --build . --config Release