os: windows

install:
  - choco install conan --params="'/AddToPath:1'"

matrix:
    include:        
        - language: cpp
          script:
            - cmd //c "RefreshEnv.cmd & conan.exe -v" 
            - conan -v
            - mkdir build
            - cd build
            - cmake ..
            - cmake --build . --config Release