os: windows

install:
  - choco install -y conan
  - RefreshCmd.cmd
  - conan -v

matrix:
    include:        
        - language: cpp
          script:
            - mkdir build
            - cd build
            - cmake ..
            - cmake --build . --config Release