os: windows

install:
  - choco install conan --params="'/AddToPath:1'"

matrix:
    include:        
        - language: cpp
          script:
            - RefreshEnv.cmd
            - mkdir build
            - cd build
            - cmake ..
            - cmake --build . --config Release