os: windows

install:
  - choco install conan --params="'/AddToPath:1'"

matrix:
    include:        
        - language: cpp
          script:
            - mkdir build
            - cd build
            - cmd //c "RefreshEnv.cmd & cmake .."
            - cmake --build . --config Release